### ISSUE TITLE
System testing using "pip install ." to 1) catch bugs before pushing to pypi; 2) avoid 'fake' contributions to downloads

### ISSUE THREAD

**Issue by leeping-ng** [aimakerspace/PeekingDuck#252]
D.O.D.

- [x] Local `pip install .` and test
- [ ] Find way to avoid/minimise 'fake' contributions to downloads on pypi

**Comment by jwaycube** [comment]
This task will be be a good task to migrate into [composite-actions](https://github.blog/changelog/2020-08-07-github-actions-composite-run-steps/)

**Comment by jwaycube** [comment]
[this approach](https://github.community/t/path-to-action-in-the-same-repository-as-workflow/16952) was used to run composite-actions on the local.
