### ISSUE TITLE
Wildcard input type for general nodes like csv writer

### ISSUE THREAD

**Issue by leeping-ng** [aimakerspace/PeekingDuck#257]
csv_writer output information based on all inputs

1. node need to be able to receive all information
2. node use a list of variables for output
3. (stretch goal) only output numeric data

- csv writer inputs: cannot be configured on run
- users may want to configure what is output in the run

**Comment by jwaycube** [comment]
Approach that will be taken:

- Enable wildcard/reserved-keyword: `input: ["*"]` / `input: ["all"]`
- Pipeline to check for wildcard input
