### ISSUE TITLE
Make GitHub actions only run on master repo, and not forks

### ISSUE THREAD

**Issue by leeping-ng** [aimakerspace/PeekingDuck#277]
**Issue:**
- Pushes to forked repos are failing due to absence Github action workflows

![image](https://user-images.githubusercontent.com/33995028/123904607-5bebaa80-d9a3-11eb-881d-f87d00cdff4a.png)

**Proposed solution:**
- Disable actions for non-master repos
https://github.community/t/have-github-action-only-run-on-master-repo-and-not-on-forks/140840/18
![image](https://user-images.githubusercontent.com/33995028/123904501-2777ee80-d9a3-11eb-9bea-708fe2b45655.png)

**Comment by jwaycube** [comment]
The solution mentioned above keeps an unintended side effect. The action runs, but terminates earlier (which is not the desirable behavior we want). Instead the behavior we want is for the action to NOT RUN in the first place. This is still an [open issue](https://github.com/actions/runner/issues/859)

**Comment by jwaycube** [comment]
At this moment, there is no code level solution to manage this issue. The most viable solution is asking contributors who have `schedule` run active on their branch to disable the run. 

Hopefully there will be a solution for this in future, possibly from this [open issue](https://github.com/actions/runner/issues/859)

Related threads:

- https://github.community/t/stop-github-actions-running-on-a-fork/17965/3
- https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow

**Comment by leeping-ng** [comment]
We realised that there is a benefit to allow Github actions to run on forked repo, it really helps with troubleshooting of our CI/CD for issue #373. Therefore, we will keep it this way and close this issue.
