### ISSUE TITLE
Link to local IHL research

### ISSUE THREAD

**Issue by leeping-ng** [aimakerspace/PeekingDuck#346]

**Comment by jovi-s** [comment]
Add references to local IHL research in our repo: NTU, NUS, etc. The closer to what we have, the better

A few possibilities:
1) SEA AI Lab and NUS LV group developed the VOLO algorithm
2) NTU Kinetics dataset (something like that)

If no link, need to think of how to weave together. High level for each paper (what it does, why it's good, who did it, performance etc.)

**Comment by jovi-s** [comment]
- 5 or 6 bullet points for each potentially relevant paper
- look at abstract, results, and conclusion
- The more difficult task is finding which papers out of the whole SG pool are more relevant for peekingduck

**Comment by jovi-s** [comment]
- Indicate the academic papers and sources used in building PeekingDuck
- Cite some local IHL papers

**Comment by jovi-s** [comment]
Add high level references of academic papers to local IHL research in repo: NTU, NUS, etc.
