### ISSUE TITLE
Deprecate scripts for mypy and linting

### ISSUE THREAD

**Issue by jwaycube** [aimakerspace/PeekingDuck#360]
### Description
pyproject.toml is able to handle configurations to help with linting and tests. It works with mypy and pylint. There needs to be exploration of pytests with the pyproject to check if pyproject can handle unit test setups.

D.O.D.

- [ ] Deprecation and removal of `scripts/check_type.sh` and `scripts/linter.sh`
- [ ] Possible deprecation of `scripts/run_tests.sh`

**Comment by leeping-ng** [comment]
The scripts are still useful for running local tests before pushing to GitHub, to avoid having to push multiple times before the checks pass. There are multiple arguments for some of the tests such as `mypy`, to the point where it doesn't make sense to deprecate the script and run it from CLI with all these arguments every single time.
