### ISSUE TITLE
Linux throws exception for `input.live` when ending output.screen with `q`

### ISSUE THREAD

**Issue by leeping-ng** [aimakerspace/PeekingDuck#427]
**Issue**: 
- The following happens when using `input.live` with `output.screen` and `q` is pressed to terminate.
- It only happens on Linux and not for MacOS or Windows
```
2021-08-16T21:41:38 peekingduck.pipeline.nodes.input.live INFO:Frames Processed: 100 ...
FATAL: exception not rethrown
Aborted (core dumped)
```

**Root cause**:
- Caused by threading in `input.live`. If the `thread.join()` is used when `q` is pressed, the problem goes away.

**Possible solutions**:
1. Make `input.live` receive `pipeline_end` as an input and use this to activate `thread.join()` using the following code.
It has 2 disadvantages: (a) this node needs to take in both "none" and "pipeline_end", which violates our rule of node inputs being outputs of previous nodes. It also piggybacks on "none" as first input so that the pipeline check doesn't fail. (b) if there's another node after `output.screen`, the error still happens because the thread is only joined at `input.live` and not this node.
**Update**: It appears that self.started in release() is the key rather than self.thread.join()

- Update read.py with:

```
class VideoThread:
    '''
    Videos will be threaded to prevent I/O blocking from affecting FPS.
    '''

    def __init__(self, input_source: str, mirror_image: bool) -> None:
        self.stream = cv2.VideoCapture(input_source)
        self.mirror = mirror_image
        if not self.stream.isOpened():
            raise ValueError("Camera or video input not detected: %s" % input_source)

        self.started = True
        self._lock = Lock()
        self.thread = Thread(target=self._reading_thread, args=(), daemon=True)
        self.thread.start()

    def release(self) -> None:
        self.started = False
        self.thread.join()
        self.stream.release()

    def _reading_thread(self) -> None:
        '''
        A thread that continuously polls the camera for frames.
        '''
        while self.started:
            _, self.frame = self.stream.read()
            self._lock.acquire()
            self._lock.release()
           
```
- Update live.py with 
```
        if "pipeline_end" in inputs:
            if inputs["pipeline_end"]:
                self.logger.info('Terminate command received.')
                self.videocap.release()
```
- Update live.yml with 
```
input: ["none", "pipeline_end"]
```

2. Make both `input.live` and `input.recorded` return `videocap` to `output.screen`. Use `output.screen` to join the thread once `q` is pressed. 
- This addresses the issue of solution (1) as the thread is joined immediately, but is as simple to implement as solution (1).
- Disadvantage: another output/input for these 3 nodes

3. Use the class VideoNoThread which is the default for `input.recorded`. Add a config to choose threading/no-threading for `input.live`, and make no-threading the default. Write a comment that threading doesn't work for Linux beside the config.
- Disadvantage: significant drop in FPS without threading, from 23 to 17 which is about 25%!

4. Move all threading to `runner` level so that threads can be managed at higher level.

**Comment by sidney-tio** [comment]
Trying to run solution 2 results in the following error; it can be traced back to the `deepcopy` operation which does not work on videoCapture objects

![image](https://user-images.githubusercontent.com/35787241/129660331-90d764cf-804b-469c-8337-d4390e05e2ae.png)
