### ISSUE TITLE
Test `input.live` and `output.screen` nodes in CI/CD

### ISSUE THREAD

**Issue by leeping-ng** [aimakerspace/PeekingDuck#433]
Example of publicly available RTSP feed:
https://ipvm.com/forums/video-surveillance/topics/need-rtsp-url-to-test-with

**Comment by ongtw** [comment]
`input.live` test with RTSP video is covered in input threading unit test for #523.

**Comment by leeping-ng** [comment]
We have not been able to come up with a method to effectively test `output.screen` in a headless environment (Github actions). As the test for `input.live` has already been added, we will close this issue.
