### ISSUE TITLE
temp.zip file causing badZipFile.

### ISSUE THREAD

**Issue by UltraRaptorYT** [aimakerspace/PeekingDuck#484]
The following is the error I got when I first tried to run the `peekingduck run`. When I look into the files, temp.zip is created but cannot be extracted as it is an empty zip file. I have tried to uninstall and reinstall but it doesn't seem to do the trick. May I get some guidance to solve this error? Thank You. 
![image](https://user-images.githubusercontent.com/62703912/137632323-966969fa-d6cf-4f32-a1eb-e49db4e8b456.png)
![image](https://user-images.githubusercontent.com/62703912/137632376-a9c631c7-f3b9-4997-b6ef-3ea583fc42bf.png)

**Comment by leeping-ng** [comment]
Hi @UltraRaptorYT, could you try the following:
1. Run `peekingduck --version` and let us know which version you are using
2. From your logs, it appears that you are using Python 3.9 - we currently are not supporting this version of Python yet. Could you try using Python 3.8 and see if it works?

**Comment by UltraRaptorYT** [comment]
![image](https://user-images.githubusercontent.com/62703912/137653496-cb0e4c12-23ed-42f1-ba35-a3d3c8aa01b3.png)
I think there are some error when i tried to run the --version command. I try to use python 3.8 to run but it doesn't seem to work. I think it is due to my environment not working ah.

**Comment by leeping-ng** [comment]
In your Python 3.8 environment, could you `pip install peekingduck==1.0.3` and see if it works?

**Comment by leeping-ng** [comment]
Hi @UltraRaptorYT, did it manage to work for you?

Thanks for raising this issue, we fixed it in #489 where PeekingDuck can only be installed when using Python 3.6, 3.7 or 3.8. This takes effect from `peekingduck==1.1` onwards.

**Comment by UltraRaptorYT** [comment]
Hi @leeping-ng, 
I managed to make it work in the Python 3.7.7 environment.
Thank you
