### ISSUE TITLE
Allow class names in object detection list (Todo: Unit Tests for YoloX)

### ISSUE THREAD

**Issue by ongtw** [aimakerspace/PeekingDuck#488]

**Comment by ongtw** [comment]
Outstanding Task: Write unit tests for YoloX.

Update: encountered torch RuntimeError on M1 Mac, possible PyTorch and torchvision conflict. See error log attached. Will continue to work on this to find a solution.

[M1_Mac_torch_error_log.txt](https://github.com/aimakerspace/PeekingDuck/files/7726374/M1_Mac_torch_error_log.txt)

**Comment by ongtw** [comment]
Finally got `node-v1.2` branch (along with YoloX) to run on M1 Mac MacOS Big Sur by doing the following:
1. Create new conda env with Python 3.8
2. Follow the instructions to install Peeking Duck on M1 Mac
3. Install pytorch and torchvision
a. `conda install pytorch-cpu`
b. Download torchvision source: `git clone https://github.com/pytorch/vision.git`
c. Compile source: `MACOSX_DEPLOYMENT_TARGET=11.6 CC=clang CXX=clang++ python setup.py install`
d. Modify installed torch package: edit
`/opt/homebrew/Caskroom/miniforge/base/envs/pkd/lib/python3.8/site-packages/torch/ao/quantization/__init__.py`
and add after last line
`from .stubs import * `

Now PKD `node-v1.2` will run with YoloX.

NB: Without 3(d) above, one will encounter the following error:
`2021-12-16 22:07:36 root  ERROR:  ImportError: cannot import name 'QuantStub' from 'torch.ao.quantization' (/opt/homebrew/Caskroom/miniforge/base/envs/pkd/lib/python3.8/site-packages/torch/ao/quantization/__init__.py)`

**Comment by ongtw** [comment]
Update: To generate M1 Mac `pytorch` and `torchvision` pip wheels and/or conda packages
- Host internally for users to download

**Comment by leeping-ng** [comment]
This has been included in the recent `1.2.0` release.
