### ISSUE TITLE
Setting weights_dir

### ISSUE THREAD

**Issue by fuzziebrain** [aimakerspace/PeekingDuck#516]
First, I'd like to thank the team for a great product that will surely help more people learn and adopt computer vision in their projects.

I have one little ask. It looks like we are not able to specify a custom directory for storing weights. I came across this issue when attempting to use PeekingDuck within an Oracle Cloud Function. Within the function, we only have write permissions to the `/tmp` directory, so it would have been nice if I could set `weights_dir` to something like `/tmp/peekingduck_weights`. Currently, my workaround (as advised by Lee Ping) is to download models during the build phase. This bloats the Docker image that I am creating for the function.

Thank you for your consideration.

**Comment by leeping-ng** [comment]
Thanks for bringing up this issue! 

Currently, a `peekingduck_weights` folder will be created in the same level as where peekingduck was installed, and model weights will be saved there the first time the model is run.
```
site-packages
|-- peekingduck
|-- peekingduck_weights
```
The `weights_dir` config was meant for PeekingDuck to locate the model weights, and it wasn't meant to be modified by users. Here's what we'll do next:
1. Look into your suggestion, and if feasible, implement it in a future release
2. If not feasible, we should update our documentation and make it clear that `weights_dir` is not meant to be modified, to prevent future confusion

**Comment by leeping-ng** [comment]
@fuzziebrain we just released v1.1.1 today, and you'll now be able to change where weights are downloaded via the `weights_parent_dir` for all our models. We have also updated our documentation accordingly.
