### ISSUE TITLE
Error while installing peekingduck in windows

### ISSUE THREAD

**Issue by nived00015** [aimakerspace/PeekingDuck#567]
Hi all,

I am facing some issue in installing peekingduck

attaching the issue here

ERROR: Could not find a version that satisfies the requirement opencv-python==4.1.2.30 (from peekingduck) (from versions: 3.4.0.14, 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 3.4.14.51, 3.4.14.53, 3.4.15.55, 3.4.16.57, 3.4.16.59, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48, 4.5.2.52, 4.5.2.54, 4.5.3.56, 4.5.4.58, 4.5.4.60)

ERROR: No matching distribution found for opencv-python==4.1.2.30 (from peekingduck)

Kindly help to resolve the issue

**Comment by liyier90** [comment]
Hi @nived00015, may I know what is your Python version?

**Comment by nived00015** [comment]
Python 3.9 @liyier90

**Comment by liyier90** [comment]
PeekingDuck is currently officially supported on Python 3.6, 3.7, and 3.8 only.

Could you please try using one of the Python versions mentioned above and see if you are able to install PeekingDuck?

**Comment by leeping-ng** [comment]
Hi @nived00015, we have just released version `1.2.0` which now supports Python 3.9 - feel free to try it out.
