### ISSUE TITLE
OpenCV Window Very Small on Ubuntu 18.04

### ISSUE THREAD

**Issue by ongtw** [aimakerspace/PeekingDuck#638]
The opencv `imshow` window is very tiny on Ubuntu 18.04 (running on Nvidia Jetson series).
Below is a screenshot from `peekingduck --verify_install` on a 1920x1080 desktop.
The video size is 710x540, which means it ought to occupy more than 1/3 (710/1920 = 36.8%) of the screen, but clearly it is way smaller than that. The xterm window is half the screen, so the video window looks like 1/6 of the screen.
This does not happen with macOS or Windows.

![Screen Shot 2022-04-04 at 12 10 55 PM](https://user-images.githubusercontent.com/13075447/161473501-3829bce0-8966-486b-8247-65edd86ea631.png)

**Comment by ongtw** [comment]
The small window seems to be caused by the type of input. Below image shows using an image as input instead of a video, and the output window is much larger and visually proportional for the 710x540 image.
The output window size for videos could be affected by the video resolution (vs video size).

![Screen Shot 2022-04-04 at 4 55 55 PM](https://user-images.githubusercontent.com/13075447/161682702-9c814719-08fd-4596-96e9-0ef1ba189cf9.png)

**Comment by liyier90** [comment]
Does the changes introduced in PR https://github.com/aimakerspace/PeekingDuck/pull/669 resolve this issue?

**Comment by ongtw** [comment]
Yes, the PR #669 did solve this issue, thanks!
Screenshots below: left = before PR #669, right = after PR #669

![image](https://user-images.githubusercontent.com/13075447/180642738-4bffe25c-2c87-4036-8bb5-206e2273538c.png)

**Comment by ongtw** [comment]
Resolved by PR #669
