### ISSUE TITLE
'peekingduck' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by nived00015** [aimakerspace/PeekingDuck#643]
Hi team, 
when i am doing peekingduck  init , i am getting this error

'peekingduck' is not recognized as an internal or external command,
operable program or batch file.

Could anyone tell why this happens ?

**Comment by leeping-ng** [comment]
Hi, could you verify if peekingduck was correctly installed on your system by following this guide: https://peekingduck.readthedocs.io/en/stable/getting_started/02_standard_install.html

If you have installed peekingduck previously using a virtual environment, do ensure that your terminal is in the virtual environment before running any `peekingduck` commands.
